document.writeln("<style type=\'text/css\'>");
document.writeln("	body,a{");
document.writeln("		cursor: url(http://static.sdg-china.com/dn/pic/dn/web10/meat2.cur ), auto;");
document.writeln("	}");
document.writeln("	#move_img{");
document.writeln("		position:absolute;");
document.writeln("		display:none;");
document.writeln("		z-index: 10000;");
document.writeln("		transition:all linear .3s;");
document.writeln("	}");
document.writeln("	/*闆�*/");
document.writeln("	.snow-container{position: fixed; top: 0; left: 0; right: 0; bottom: 0; pointer-events: none; z-index: 100001;}");
document.writeln("</style>");
document.writeln("<img id=\'move_img\' src=\'http://static.sdg-china.com/dn/pic/dn/web10/mcdh02.gif\' />");
document.writeln("<!--闆櫙 start-->	");
document.writeln("<div class=\'snow-container\'></div>");
document.writeln("<!--闆櫙end-->	");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("$(function() {");
document.writeln("	$(document).mousemove(function(e) {");
document.writeln("		$(\'#move_img\').css({");
document.writeln("			\'opacity\':\'1\',");
document.writeln("			\'display\':\'block\',");
document.writeln("			\'top\': (e.pageY - 50) + \'px\',");
document.writeln("			\'left\': (e.pageX + 50) + \'px\'");
document.writeln("		});");
document.writeln("	});");
document.writeln("});");
document.writeln("</script>");